genclasif:
    name: genCharmFilterRDF
    path: ttbar.Modules.GenFilter
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        name: self.dataset.process.name

puweight:
    name: puWeightRDF
    path: Corrections.LUM.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

jet_smearing:
    name: jetSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jerTag: self.config.year
        isUL: self.dataset.has_tag('ul')


jet_smear_val:
    name: jetVarRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC


met_smearing:
    name: metSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC

wqq_channel:
    name: selectionWQQRDF
    path: ttbar.Modules.selection_wqq_fj
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isMU: self.dataset.has_tag('muon')

PUjetID_SF:
    name: PUjetID_SFRDF
    path: Corrections.JME.PUjetID_SF
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        isUL: self.dataset.has_tag('ul')

muSF:
    name: muSFRDF
    path: Corrections.MUO.muCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

eleSD:
    name: eleSFRDF
    path: Corrections.EGM.eleCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

btagSF:
    name: btag_mySFRDF
    path: ttbar.Modules.btag_mycorrection
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')


